[package]
name = "globals_benchmarks"
version = "0.1.0"
authors = ["Jakob Meier <inbox@jakobmeier.ch>"]
edition = "2018"

[dependencies]
lazy_static = "=1.4.0"
once_cell = "=1.8.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false